version: "3.8"

services:
  nginx:
    image: nginx:1.19.8-alpine
    restart: always
    volumes:
      - ./services/revproxy/nginx/templates.prod:/etc/nginx/templates
      - ./services/revproxy/nginx/ssl:/etc/ssl
    environment:
      - PROXY_PASS_BACKEND
      - PROXY_PASS_FRONTEND
    ports:
      - "443:443"
    networks:
      - backend

  frontend:
    image: registry.gitlab.com/rtk-sjm/webosrtkadmin/admin-frontend:0.2.0
    build:
      context: ./services/frontend
    restart: always
    environment:
      - VUE_APP_API_URI=${API_URI}/api/v1
      - VUE_APP_API_PROTO=https
    networks:
      - backend

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rtkrms
    networks:
      - backend

networks:
  backend: